language: python
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
# - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -m tests.datasetCreation < testing.txt
  - python -m tests.KernelRegularizedLeastSquares
  - python -m tests.ParameterSelection
